### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/wheelie-big-and-small#1]
# Plan

Task list

- [x] Create itch page draft, validate running in browser fine. @TheDuckCow
- [ ] ~~UV wheel animator @vertenflow along with texture~~ will be black
- [x] Base shader for world @vertenflow
- Create the actors/vehicle controller - including size changing ~~@TheDuckCow~~  -> @gialonsoser
  - [x] Visual size changing with speed
  - [x] Update position / colliders to coincide with the speed changes 
  - [x] Swap in final vehicle and tweak positions
- Obstacles:
  - Functional "death barrel" -> @gialonsoser
  - Any other obstacles
- [x] Create first two sample prefab road scene @TheDuckCow 
- [x] Menu screen + transition system @TheDuckCow 
- [x] Road Planner: Mechanism to load next segment of road/environmental @TheDuckCow 
- [x] Game over/restart screen / trigger @TheDuckCow
- [x] Vehicle models for the road @ogbog 
- [x] Placement of vehicles onto road lanes with movement @TheDuckCow 
- Road elements @robocognito  / @vertenflow 
  - [x] Grated bridge (with holes, large car only)
  - [ ] Bridge style 2, skinny bridge (smol car only)
  - [ ] Tunnel prefab
  - [x] Overpass
  - [x] Road signs
- Scene environments for Memphis Style @robocognito 
  - [x] Trees
  - [x] Rocks
  - [ ] Abstract decals / alphacard
  - [ ] Grass textures / alphacard
  - [ ] Background envior map suited to the style
- [x] Decoration of the saved road scenes @ogbog / @robocognito 
- [x] Main player character model from Felix via @ogbog , for @gialonsoser to integrate into the project
